// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA321pVbXsz4jr99EJs5WNt9DnNt-BNE1o',
    appId: '1:606136581372:web:d3042777d69d35ca7c2b79',
    messagingSenderId: '606136581372',
    projectId: 'sriracha-92159',
    authDomain: 'sriracha-92159.firebaseapp.com',
    databaseURL: 'https://sriracha-92159-default-rtdb.firebaseio.com',
    storageBucket: 'sriracha-92159.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAenh_ufJ1tExFxckcEG6182PfEPKeJ_NE',
    appId: '1:606136581372:android:941b5fa8cee8c71f7c2b79',
    messagingSenderId: '606136581372',
    projectId: 'sriracha-92159',
    databaseURL: 'https://sriracha-92159-default-rtdb.firebaseio.com',
    storageBucket: 'sriracha-92159.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH0safxKxBCuRjkkxgFy6QgmjOanZq1N8',
    appId: '1:606136581372:ios:d7891bf2a50a17897c2b79',
    messagingSenderId: '606136581372',
    projectId: 'sriracha-92159',
    databaseURL: 'https://sriracha-92159-default-rtdb.firebaseio.com',
    storageBucket: 'sriracha-92159.appspot.com',
    androidClientId: '606136581372-05svg60rt3k0618s03oqkj9a7l5a1cur.apps.googleusercontent.com',
    iosClientId: '606136581372-b9oj29810v09p3ugbt89io2g9g2l56ua.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH0safxKxBCuRjkkxgFy6QgmjOanZq1N8',
    appId: '1:606136581372:ios:d7891bf2a50a17897c2b79',
    messagingSenderId: '606136581372',
    projectId: 'sriracha-92159',
    databaseURL: 'https://sriracha-92159-default-rtdb.firebaseio.com',
    storageBucket: 'sriracha-92159.appspot.com',
    androidClientId: '606136581372-05svg60rt3k0618s03oqkj9a7l5a1cur.apps.googleusercontent.com',
    iosClientId: '606136581372-b9oj29810v09p3ugbt89io2g9g2l56ua.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
